id: PEEAB4045
initial_creation_type: input
source_metadata:
  title: Sang Offering
  language: es
  description: 'Texts on the subject of Sang (bsang/bsangs) or Purificatory Incense
    Smoke Offering:'
  volume:
    f09556b729d6490a8338e86631e56501:
      title: A Guide to the Practice of Sang
      parent: Commentaries
    dbc4cf0a8e814b7ea9025f4f19483488:
      title: The Gentle Rain of Benefit and Joy - An Explanation of the Practice of
        Sang Offering
      parent: Commentaries
    94438b406c3e4f81846b6633c608aed2:
      title: Yarlha Shampo Sang Offering
      parent: Dharma Protectors
    d0d836de496a429399876931aff4732a:
      title: Short Sang Offering to Kurukullā
      parent: Kurukullā
    3081f1387e8e45e29985847050919ec9:
      title: 'The Lotus Net: A Sang Offering to the Mighty Lotus Ḍākinī, Kurukullā'
      parent: Kurukullā
    2e75c88fe7024133820189489d2c2eca:
      title: 'The Concise Cleansing Offering from The Guru’s Heart Practice: Dispelling
        All Obstacles on the Path'
      parent: Rituals
    2f9071241dc5404a8b5d8ac9e9819b9f:
      title: Sang Offering to Yellow Jambhala
      parent: Rituals
    28e4d218a1f2429998f22482ea27bdef:
      title: Brief Smoke Offering to the Great Lion of the World
      parent: Rituals
    cf279e62a5f642c4be8c87636e715bf1:
      title: 'Lasel Chenmo: A Sang Offering to the Nāgas'
      parent: Rituals
    c44201b5d6c84ec2bfd03c1cd7f456d3:
      title: Brief Sang Offering
      parent: Rituals
    4690620d9a6a41818916cc8b842a3182:
      title: Brief Sang Offering to Purify Contamination
      parent: Rituals
    b223921368714f5788a7107196d4231c:
      title: 'Divine Blue Water: A Contamination Purifying Smoke Offering by the Great
        Master Padmasambhava'
      parent: Rituals
    2e1a9b45a2e04a0facdaeae359e894ab:
      title: Mountain Smoke Offering from The Life-Force Practice of the Vidyādharas
      parent: Riwo Sangchö
    8b24a2f837a24efc95878ce898c8c918:
      title: The Mountain Smoke Offering (Riwo Sangchö)
      parent: Riwo Sangchö
    8e0a2d1cb2b941dbbcb9a92601fa9069:
      title: The Mountain Smoke Offering Arranged for Recitation
      parent: Riwo Sangchö
    4f389feeece44c37b0e888187b7f6567:
      title: A Concise Sang Offering to Tārā
      parent: Tārā
created_at: '2022-03-01T05:40:37.292337'
last_modified_at: '2022-03-01T05:40:37.292340'
